### PR TITLE
deep south devs

### PR DESCRIPTION
**Pull request by theonlysinjin**
Add [deep south devs](https://www.meetup.com/deepsouthdevs/)

### CODE REVIEW

**Comment by schalkventer** [comment]
Looks good to me! @theonlysinjin just checking is it intentionally styled in lowercase, or are you happy to just to style it as a proper noun for consistency in the list (if the styling is not intentional)?

**Comment by theonlysinjin** [comment]
Thought that might come up, it's styled intentionally as that's how it appears on LinkedIn etc.
I agree it does not fit with the others at the moment, but as the list grows it might?

**Comment by theonlysinjin** [comment]
Happy to revisit this at a later point but would like to help grow the list. This is a great initiative.

**Comment by schalkventer** [comment]
Just wanted to approve this with the lower case :) 

But lets just then go with the change then just to have it in the list. @theonlysinjin

**Review by schalkventer — APPROVED** [review]

**Pull request merged**
